dist: xenial
language: node_js
node_js: [node]
cache: yarn
install: yarn install --frozen-lockfile
script:
- yarn ci-lint
- yarn release
- yarn bundlesize
- cp README.md dist/
deploy:
  provider: pages
  skip_cleanup: true
  github_token:
    secure: "XWIe9W4umv3OysOGnfEUXdsTB+2VXlTSVx5XjFyMpONhocW5dYCnsFxGNGGPnBREL4vAcOejK5DHo1z/1yjr9XyhIv6uo14gAQ55bS84CcAWx1OnmP1gZG3hbWTn+wKJYC4zoolymq98ySNkac6vAin8OTWQrLn72HHw1TGkDWZS96rOf0I6cb89chC28dxtq1enmk77fnZc4kkHF2s9qEmfb5L4hrNfe8yksj2DXyT9viXugQxByN4kYqT+eR/DUar9UmtZu48nr++cQtWOV5oYBt020enMWwqR4L0HWLU8cNS26MO6QDQ+ZqHCBjVDpEQtoBkAmexuHV/x6HASkn52SNv0wbbuhsngUzAqHkvYgFS4x8RHUMcaWxD1MHyRIgrJdUT8N/7qBtxjqK4khD3GM6Jory3XNN1CQsnujKhkG4uWJoW+Vf7fVgEFiOdtalsM1n61q4uwA+0AKAPGxV8OjXi55V7mRUi2dZVZsFIWKsUojB/0h0EY7BHD1EJbDa3y6O6WxQ0om2ZGVUHJhWxl3eg/XUnsNEBVr0bVu3R/tOJevYVCKYnEUwCzm7GMtQHZYGF8YALBuYLZEzOyo46nlQflGMYyunWkcd3jmJmljpPY6HODbZIF05gP61qAxfzPWWHH8I0Vjxk5QBWsbcMg5a8opRYSJFEzZphddK4="
  keep_history: true
  local_dir: dist
  target_branch: master
  on:
    branch: source
env:
  global:
    - secure: "Rqxjm/CZad6zO/cK2RLEcZvz3nYTl27RWhCH02VUWvYhSSbKok2i/p/sBy8CdsraxGZQg84nI7xhDbYgHJvKPOCWgRL2CrVkiZAceBRvWpriUbUOeZwHgWaTfn9J24GDNZNwYC4DF4Q3btr1S3sewfy63c0h7UVB4Eq1lHBDNX2l7OL3zRo38cEeT03N3nsitPLzrow0NdsfxwCDIfTBPgchn444ce6yE6vao6kbSuK1OTTTeiKya2SwBxQSGg4Ip7JMEOlkAQEAX4uoo6ZTkzxTPcpoU9o13y7/U0cReFYY/ZEDJZyibqcRE+J98NbJo5+d1sc0HrlktSNeio/cQFFXbpPTcFgL/UVeEMX2qLHL70lHH/xQi8ex6SlVmfuWi4gLRDQzl6Qx0ZEiUHX71DkfEbseTsq+zpHx4HdTI1DTk9ySV3UqY7i/0x14PV//3lkpEQo8w85YwW4noKl2YddrYSUFx6GXIBxnBrVp8zkokBvCAIPC1TCJQbvRIA/NHBMvxQJ7mvIWeG8673OYdIrFbqTnTvtDryELlK1Hj2Yshd9T9c/L6IhdE9F2r7RrQhHmLtHdjXfgucTgcr9myXhw2sExlg84f+JS9j5N0tyncJAka3ht3DrgYymOAkEyw0DozZg2qHrQIeETYdCc7ScfCXdMO6dEJSHbfmpJIsA="
